spring.application.name=OAuth2Authentication
server.port=8085

#Google
spring.security.oauth2.client.registration.google.client-id=< YOUR-CLIENT ID > 
spring.security.oauth2.client.registration.google.client-secret=< YOUR-CLIENT-SECRET >